config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "study_participants#index"

  resources :data_collection_events, only: [:show]

  resources :personal_information, only: [:edit]

  resources :studies, only: [:show] do
    resources :study_participants, only: [:new, :create, :index]
    resources :study_protocols, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/data_collection_event.rb
class DataCollectionEvent < ApplicationRecord
  belongs_to :study

  validates :collected_at, presence: true

  after_initialize :set_defaults

  private

  def set_defaults
    self.collected_at ||= Time.zone.now
  end
end

app/models/personal_information.rb
class PersonalInformation
  delegate :email, to: :study_participant
  delegate :first_name, to: :study_participant
  delegate :last_name, to: :study_participant

  def initialize(study_participant_id = nil)
    @study_participant_id = study_participant_id
  end

  def study_participant
    @study_participant ||= StudyParticipant.find(@study_participant_id)
  end
end

app/models/study.rb
class Study < ApplicationRecord
  has_many :study_participants, dependent: :destroy
  has_many :data_collection_events, dependent: :destroy
  has_one :study_protocol, dependent: :destroy

  validates :name, presence: true
end

app/models/study_enrollment.rb
class StudyEnrollment
  attr_reader :study_participant

  def initialize(study_participant_params)
    @study_participant_params = study_participant_params
  end

  def create
    @study_participant = StudyParticipant.new(study_participant_params)

    if @study_participant.save
      send_welcome_email
    else
      false
    end
  end

  private

  attr_reader :study_participant_params

  def send_welcome_email
    StudyParticipantMailer
      .with(study_participant: study_participant)
      .welcome_email
      .deliver_later
  end
end

app/models/study_participant.rb
class StudyParticipant < ApplicationRecord
  belongs_to :study

  validates :email, presence: true
end

app/models/study_protocol.rb
class StudyProtocol < ApplicationRecord
  belongs_to :study
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable

  enum role: {
    technician: 0,
    co_investigator: 1,
    principal_investigator: 2,
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  before_action :authenticate_user!
end

app/controllers/data_collection_events_controller.rb
class DataCollectionEventsController < ApplicationController
  def show
    @data_collection_event = DataCollectionEvent.find(params[:id])
  end
end

app/controllers/personal_information_controller.rb
class PersonalInformationController < ApplicationController
  def edit
    @personal_information = PersonalInformation.new(params[:id])
    flash[:warning] = I18n.t("personal_information.edit.warning")
  end
end

app/controllers/studies_controller.rb
class StudiesController < ApplicationController
  def show
    @study = Study.find(params[:id])
  end
end

app/controllers/study_participants_controller.rb
class StudyParticipantsController < ApplicationController
  def index
    @study_participants = StudyParticipant.where(study_id: params[:study_id])
  end

  def new
    @study_participant = StudyParticipant.new(study: study)
  end

  def create
    enrollment = StudyEnrollment.new(study_participant_params)

    if enrollment.create
      redirect_to study_study_participants_path
    else
      @study_participant = enrollment.study_participant
      render :new
    end
  end

  private

  def study
    @study ||= Study.find(params[:study_id])
  end

  def study_participant_params
    params.require(:study_participant)
      .permit(:first_name, :last_name, :email)
      .merge(study_id: params[:study_id])
  end
end

app/controllers/study_protocols_controller.rb
class StudyProtocolsController < ApplicationController
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def new
    @study_protocol = StudyProtocol.new(study: study)
    authorize(@study_protocol)
  end

  def create
    @study_protocol = StudyProtocol.new(study_protocol_params)
    authorize(@study_protocol)

    if @study_protocol.save
      redirect_to study_path(study)
    else
      render :new
    end
  end

  private

  def study
    @study ||= Study.find(params[:study_id])
  end

  def user_not_authorized
    flash[:alert] = "Only Principal Investigators may create study protocols"
    redirect_back(fallback_location: root_path)
  end

  def study_protocol_params
    params.require(:study_protocol)
      .permit(:instructions)
      .merge(study_id: params[:study_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/data_collection_events/show.html.erb
<div class="summary-information">
  <dl>
    <dt>"Collection Date:"</dt>
    <dd class="collected-date"><%= l(@data_collection_event.collected_at, format: :long_date_only)%></dd>
  </dl>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EvaluatingAlternatives</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:warning] %>
      <div class="flash alert-warning" data-role="warning"><%= flash[:warning] %></div>
    <% end %>
    <% if flash[:notice] %>
      <div class="flash alert-notice" data-role="notice"><%= flash[:notice] %></div>
    <% end %>
    <% if flash[:alert] %>
      <div class="flash alert-danger" data-role="alert"><%= flash[:alert] %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/personal_information/edit.html.erb
Editing information for <%= @personal_information.first_name %>

app/views/studies/show.html.erb
<div class="heading">
  <p><%= @study.name %></p>
</div>

<% if @study.study_protocol.present? %>
  <div class="protocol">
    <%= @study.study_protocol.instructions %>
  </div>
<% end %>

app/views/study_participants/new.html.erb
<%= form_with model: @study_participant, url: study_study_participants_path do |form| %>
  <div class="field_with_errors">
    <%= form.label(:first_name, for: :study_participant_first_name) %>
    <%= form.text_field(:first_name, id: :study_participant_first_name, class: "form-control") %>
  </div>

  <div class="field_with_errors">
    <%= form.label(:last_name, for: :study_participant_last_name) %>
    <%= form.text_field(:study_participant_last_name, id: :study_participant_last_name, class: "form-control") %>
  </div>

  <div class="field_with_errors">
    <%= form.label(:email, for: :study_participant_email) %>
    <%= form.text_field(:email, id: :study_participant_email, class: "form-control") %>
  </div>

  <%= form.submit "Enroll", class: "btn btn-default action-btn" %>
<% end %>

app/views/study_protocols/new.html.erb
<%= form_with model: @study_protocol, url: study_study_protocols_path do |form| %>
  <div class="field_with_errors">
    <%= form.label(:instructions, for: :study_participant_instructions) %>
    <%= form.text_field(:instructions, id: :study_participant_instructions, class: "form-control") %>
  </div>

  <%= form.submit "Submit", class: "btn btn-default action-btn" %>
<% end %>